### ISSUE TITLE
SYS_ERROR:org.xml.sax.SAXException: value for 'proportionOfThickness' attribute in featureRange element must be between 0 and 1 in null at line 1192 column 147

### ISSUE THREAD

**Issue by ruchi19flowchart** [happykhan/BRIG#16]
Your query File:
/Data/NGS_1165_Circos_genomes/genome/Bacillus_paralicheniformis.fna
--------------------------------------
Multi-FASTA detected, Rewriting headers

Initializing XML output..

Running BLAST...
Sequence length: 3976743
Spaced1Bacillus_paralicheniformis.fna.nin exists, skipping ..
Bacillus_paralicheni... exists, skipping ..
Spaced1Bacillus_paralicheniformis.fna.nin exists, skipping ..
Bacillus_paralicheni... exists, skipping ..
Spaced1Bacillus_paralicheniformis.fna.nin exists, skipping ..
G1_gene.fnaVsSpaced1... exists, skipping ..
Spaced1Bacillus_paralicheniformis.fna.nin exists, skipping ..
Bacillus_licheniform... exists, skipping ..
Spaced1Bacillus_paralicheniformis.fna.nin exists, skipping ..
Bacillus_amyloliquef... exists, skipping ..

Parsing BLAST Results...

Rendering CGVIEW image...
java -Xmx1500m  -jar cgview/cgview.jar -f jpg  -i /Data/NGS_1165_Circos_genomes/genome/scratch/Bacillus_paralicheniformis.fna.xml -o /Data/NGS_1165_Circos_genomes/genome/Bacillus_paralicheniformis.fna.jpg
Parsing XML input.
SYS_ERROR:org.xml.sax.SAXException: value for 'proportionOfThickness' attribute in featureRange element must be between 0 and 1 in null at line 1192 column 147
SYS_ERROR:	at ca.ualberta.stothard.cgview.CgviewFactory.handleFeatureRange(CgviewFactory.java:2215)
SYS_ERROR:	at ca.ualberta.stothard.cgview.CgviewFactory.startElement(CgviewFactory.java:516)
SYS_ERROR:	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
SYS_ERROR:	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
SYS_ERROR:	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
SYS_ERROR:	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
SYS_ERROR:	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
SYS_ERROR:	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
SYS_ERROR:	at org.apache.xerces.parsers.DTDConfiguration.parse(Unknown Source)
SYS_ERROR:	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
SYS_ERROR:	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
SYS_ERROR:	at ca.ualberta.stothard.cgview.CgviewFactory.createCgviewFromFile(CgviewFactory.java:300)
SYS_ERROR:	at ca.ualberta.stothard.cgview.CgviewIO.main(CgviewIO.java:1056)
SYS_ERROR:The following error occurred: org.xml.sax.SAXException: value for 'proportionOfThickness' attribute in featureRange element must be between 0 and 1 in null at line 1192 column 147
Done.

This is what I'm getting while plotting circular plot.
Need help

**Comment by dfl5440** [comment]
Did you ever figure this out??

**Comment by happykhan** [comment]
This is a very old ticket. I am closing it. Please Try BRIG version 1.0.0 and open a new ticket if problems persist.
